src/Entity/Game.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GameRepository")
 */
class Game
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $videoGameId;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $creator;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->date = new \DateTime();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVideoGameId(): ?string
    {
        return $this->videoGameId;
    }

    public function setVideoGameId(string $videoGameId): self
    {
        $this->videoGameId = $videoGameId;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCreator(): ?string
    {
        return $this->creator;
    }

    public function setCreator(string $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/AnnonceController.php
<?php

namespace App\Controller;

use App\Entity\Game;
use App\Entity\GameSearch;
use App\Form\GameSearchType;
use App\Repository\GameRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\EntityManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Environment;

class AnnonceController extends AbstractController
{

    /**
     * @var GameRepository
     */
    private $repository;

    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(GameRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/games", name="game.index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new GameSearch();
        $form =$this->createForm(GameSearchType::class, $search);
        $form->handleRequest($request);

        $games = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            12
        );
        return $this->render('annonces/index.html.twig', [
            'games' => $games,
            'current_menu' => 'games',
            'form' => $form->createView()
        ]);
    }
    /**
     * @Route("/games/{id}", name="game.show")
     * @param Game $game
     * @return Response
     */
    public function show(Game $game) : Response
    {
        return $this->render('annonces/show.html.twig', [
            'game' => $game,
            'current_menu' => 'games'
        ]);
    }

}

templates/annonces/index.html.twig
{% extends 'base.html.twig'%}

{% block title 'blablabla' %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.dayChoice) }}
                </div>
                <div class="col">
                    {{ form_row(form.gameChoice) }}
                </div>
                <div class="col">
                    <div class="form-group">
                        <button class="btn btn-primary">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container mt-4">
        <h1>Voir toutes les annonces</h1>

        <div class="row">
            {% for game in games %}
                <div class="col-md-4">
                    {% include 'game/_game.html.twig' %}
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
            {{ knp_pagination_render(games) }}
        </div>
    </div>
{%  endblock %}

templates/annonces/show.html.twig
{% extends 'base.html.twig'%}

{% block title game.id %}

{% block body %}
    <div class="container mt-4">
        <h1>{{ game.id }}</h1>
        <h1>{{ game.videoGameId }}</h1>
        <h1>{{ game.creator }}</h1>
        <h1>{{ game.date|date("d/m/Y") }}</h1>
        <h1>{{ game.createdAt|date("d/m/Y") }}</h1>
    </div>
{%  endblock %}